### ISSUE TITLE
Rusttype FontCollection is missing in versions after v0.8

### ISSUE THREAD

**Issue by Horki** [silvia-odwyer/rustvis#1]
Cargo is updating to newest lib when "*" is an option, and Cargo.lock is missing

- version "rusttype" after v0.8 is missing "FontCollection"
- set fixed v0.8.3

**Comment by Horki** [comment]
@silvia-odwyer pull req. #2

**Comment by silvia-odwyer** [comment]
Since pull request #2 fixes this, I'm going to close this issue; thanks again for alerting me to this and for the PR! 😄
