### ISSUE TITLE
Time crate: depracted "to" fun

### ISSUE THREAD

**Issue by Horki** [silvia-odwyer/rustvis#4]
@silvia-odwyer in bin example there is the usage of PreciseTime diff using a function "to", which is deprecated in v0.2, so I've updated Cargo.toml to v0.1

**Comment by Horki** [comment]
pull req https://github.com/silvia-odwyer/rustvis/pull/5

**Comment by Horki** [comment]
pull req https://github.com/silvia-odwyer/rustvis/pull/5

**Comment by silvia-odwyer** [comment]
Since pull request #5 fixes this issue, I'm going to close this. Thanks again for alerting me to this @Horki :smile:
